### PR TITLE
sanctuary-def@0.20.0

### PR DESCRIPTION
**Pull request by davidchambers**
Closes #48

<https://github.com/sanctuary-js/sanctuary-def/releases/tag/v0.20.0>

### CODE REVIEW

**Comment by Avaq** [comment]
Thank you, David!

**Comment by davidchambers** [comment]
Will you publish a new version?

**Comment by Avaq** [comment]
Sorry, I got distracted. I did it. :)

**Comment by davidchambers** [comment]
Thanks!

**Pull request merged**
