### PR TITLE
Use versioned link to sanctuary-def docs

### PR DESCRIPTION
**Pull request by Avaq**

### CODE REVIEW

**Comment by Avaq** [comment]
Ah.. This causes the tests to fail with `Exact version not specified for sanctuary-def`.

**Comment by davidchambers** [comment]
Are you happy to specify an exact version?

**Comment by Avaq** [comment]
Does that mean pinning the version in `package.json` down to something like `0.15.0`?

**Comment by davidchambers** [comment]
It does, yes. We need an exact version in order to construct a permalink.

**Comment by Avaq** [comment]
I don't think that will work for me for one or more of the following reasons:

- `sanctuary-def` is a *peer* dependency of this library. I'm not sure where Transcribe looks to resolve dependency versions, but I wouldn't be surprised if it doesn't account for peerDependencies.
- I use a very small subset of sanctuary-def, which is more likely to stay unchanged across major versions. Therefore I can guarantee compatibility for a wide range of Sanctuary Def versions. Pinning the version would force my peers to install a specific version of sanctuary-def.

----

What *could* work, possibly, if I pin the version of sanctuary-def as specified in devDependencies. Would that work, @davidchambers?

**Comment by davidchambers** [comment]
> What *could* work, possibly, if I pin the version of sanctuary-def as specified in devDependencies.

That would work. [`generate-readme`][1] checks both `dependencies` and `devDependencies`. :)


[1]: https://github.com/sanctuary-js/sanctuary-scripts/blob/v1.2.0/bin/generate-readme#L33-L39

**Review by davidchambers — APPROVED** [review]

**Pull request merged**
